name: 'Overwrite docker image tag'
description: 'Overwrite docker image tag on Github Package Registry with an image of your preference'
branding:
  icon: 'delete'
  color: 'red'
inputs:
  dockerImage:
    description: 'The full docker image name and tag to be overwritten'
    required: true
  overwriteImage:
    description: 'The docker image to overwrite the docker image with'
    required: true
  authenticatingUser:
    description: 'The user we authenticate as when overwriting the docker image'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
